######################################################################
##
## Filename: da_tb.udo
## Created on: Sun Jun 30 17:15:04 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
